### ISSUE TITLE
Index out of Range.

### ISSUE THREAD

**Issue by whitebook** [ttacon/libphonenumber#10]
Passing in a bad number from a pretty big list. I get this Panic.

I will find the number and post it here. 

So it seems if the number ends 0111 is the problem.

Try for example
(555) 555-0111

I also Tried 0113 which also failed. I think it sees (011) pattern which is international dialing code from the US.

If I change it to 0133 it works fine

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/ttacon/libphonenumber.parsePrefixAsIdd(0x2083819a0, 0x2084d2af0, 0xa)
	go/src/github.com/ttacon/libphonenumber/phonenumberutil.go:2553 +0x291
github.com/ttacon/libphonenumber.maybeStripInternationalPrefixAndNormalize(0x2084d2af0, 0x208456f26, 0x3, 0x10)
	go/src/github.com/ttacon/libphonenumber/phonenumberutil.go:2593 +0x463
github.com/ttacon/libphonenumber.maybeExtractCountryCode(0x2084c6e70, 0xd, 0x20844f680, 0x2084d2a80, 0x0, 0x2084ad920, 0xe, 0x0, 0x0)
	go/src/github.com/ttacon/libphonenumber/phonenumberutil.go:2470 +0x1e8
github.com/ttacon/libphonenumber.parseHelper(0x208467a70, 0xe, 0x1c12f0, 0x2, 0x100, 0x2084ad920, 0x0, 0x0)
	go/src/github.com/ttacon/libphonenumber/phonenumberutil.go:2848 +0x519
github.com/ttacon/libphonenumber.ParseToNumber(0x208467a70, 0xe, 0x1c12f0, 0x2, 0x2084ad920, 0x0, 0x0)
	go/src/github.com/ttacon/libphonenumber/phonenumberutil.go:2731 +0x6c
github.com/ttacon/libphonenumber.Parse(0x208467a70, 0xe, 0x1c12f0, 0x2, 0x208467a70, 0x0, 0x0)
	go/src/github.com/ttacon/libphonenumber/phonenumberutil.go:2724 +0x8a
main.main()

**Comment by ttacon** [comment]
Thanks for the bug report! I'll definitely take a look at this when I can get some time to - hopefully this weekend. Thanks for the reproducible test case, too!

**Comment by ttacon** [comment]
Fixed by #14
