### ISSUE TITLE
Not go routine safe

### ISSUE THREAD

**Issue by govindarajan** [ttacon/libphonenumber#24]
Looks like this code is not go routine safe. When I try to run parallel, it is panic-ing.

Please find the trace below.

goroutine 13 [running]:
runtime.throw(0xec0ca0, 0xd)
        /usr/local/go/src/runtime/panic.go:527 +0x90 fp=0xc8204e97b8 sp=0xc8204e97a0
runtime.evacuate(0xc0dfa0, 0xc82007df80, 0x0)
        /usr/local/go/src/runtime/hashmap.go:825 +0x3b1 fp=0xc8204e9878 sp=0xc8204e97b8
runtime.growWork(0xc0dfa0, 0xc82007df80, 0x1)
        /usr/local/go/src/runtime/hashmap.go:791 +0x57 fp=0xc8204e9898 sp=0xc8204e9878
runtime.mapassign1(0xc0dfa0, 0xc82007df80, 0xc8204e99b0, 0xc8204e9978)
        /usr/local/go/src/runtime/hashmap.go:433 +0x176 fp=0xc8204e9940 sp=0xc8204e9898
github.com/ttacon/libphonenumber.isNumberPossibleForDesc(0xc8202748b0, 0xa, 0xc8201a1410, 0xc8204e9a10)
        /home/someuser/src/github.com/ttacon/libphonenumber/phonenumberutil.go:2051 +0x15e fp=0xc8204e99d8 sp=0xc8204e9940
github.com/ttacon/libphonenumber.isNumberMatchingDesc(0xc8202748b0, 0xa, 0xc8201a1410, 0x0)
        /home/someuser/src/github.com/ttacon/libphonenumber/phonenumberutil.go:2063 +0x18a fp=0xc8204e9a70 sp=0xc8204e99d8
github.com/ttacon/libphonenumber.getNumberTypeHelper(0xc8202748b0, 0xa, 0xc8201a4280, 0x2)
        /home/someuser/src/github.com/ttacon/libphonenumber/phonenumberutil.go:1983 +0x120 fp=0xc8204e9ab8 sp=0xc8204e9a70
github.com/ttacon/libphonenumber.IsValidNumberForRegion(0xc8202f8180, 0xea7c30, 0x2, 0x0)
        /home/someuser/src/github.com/ttacon/libphonenumber/phonenumberutil.go:2110 +0x245 fp=0xc8204e9ba8 sp=0xc8204e9ab8
github.com/ttacon/libphonenumber.IsValidNumber(0xc8202f8180, 0xd)
        /home/someuser/src/github.com/ttacon/libphonenumber/phonenumberutil.go:2073 +0x4d fp=0xc8204e9be0 sp=0xc8204e9ba8
bitbucket.org/Test/gondor/common/helpers/numbers.GetPhoneNumber(0xeb4f50, 0xd, 0xea6308, 0x2, 0x0, 0x0, 0x0, 0x0, 0xc8202f8120)
        /home/someuser/src/bitbucket.org/Test/gondor/common/helpers/numbers/numbers.go:62 +0x426 fp=0xc8204e9d90 sp=0xc8204e9be0
bitbucket.org/Test/gondor/gollum/gtest_test.playHangupTest(0xc820242a30)
        /home/someuser/src/bitbucket.org/Test/gondor/gollum/gtest/bulk_requests_test.go:38 +0x1f1 fp=0xc8204e9f88 sp=0xc8204e9d90
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8204e9f90 sp=0xc8204e9f88
created by bitbucket.org/Test/gondor/gollum/gtest_test.glob.func1.1.1.1
        /home/someuser/src/bitbucket.org/Test/gondor/gollum/gtest/bulk_requests_test.go:119 +0x86

**Comment by dahankzter** [comment]
I get this too.

It is the unprotected regex cache: regexCache 

Possibly a simple lock can help but I am forced to sync over the whole call which is probably more costly than skipping the regex cache. At least for large instances with lots of cores and gouroutines.

**Comment by bjones6** [comment]
@dahankzter 

How are you syncing over the whole call?

**Comment by dahankzter** [comment]
I just do something like this:

```go
	phoneLock.Lock()
	formattedNum, err := libphonenumber.Parse(phone, country)
	phoneLock.Unlock()
```

**Comment by ttacon** [comment]
Closed by https://github.com/ttacon/libphonenumber/pull/27
