### ISSUE TITLE
Better way to get initial metadata in?

### ISSUE THREAD

**Issue by ttacon** [ttacon/libphonenumber#3]

**Comment by ajankovic** [comment]
Can you please describe how are you getting metadata at the moment? There are some outstanding issues related to this and I would like to contribute if I can.

**Comment by ttacon** [comment]
Currently it's a manual process of pulling the raw metadata from the C version of libphonenumber as they store it in normal protobufs whereas the Java version, if I remember correctly, first writes the protobufs to an a Java Object file. All that is required is to move the raw data to metagen.go. Feel free to take a stab at this! But I also have another project where I'm building a tool that will address this as one of it's use cases (protobuf preloading).
