### ISSUE TITLE
Go get fails with this

### ISSUE THREAD

**Issue by raghav-g** [ttacon/libphonenumber#39]
$ **go get github.com/ttacon/libphonenumber**
# github.com/ttacon/libphonenumber

**../../../work/src/github.com/ttacon/libphonenumber/phonemetadata.pb.go:32: undefined: proto.ProtoPackageIsVersion1**

If i comment the line out, I get a panic when i do this

**fmt.Println(libphonenumber.IsNumberMatch("+91-9573750192", "9573750192"))**

**Error >>** 

panic(0x105a80, 0xc4201a6a00)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/golang/protobuf/proto.Merge(0x1b3d40, 0x0, 0x1b3d40, 0xc4201a0fc0)
    /Users/Raghav/work/src/github.com/golang/protobuf/proto/clone.go:64 +0x33c
github.com/ttacon/libphonenumber.isNumberMatchWithNumbers(0xc4201a0fc0, 0xc4201a1620, 0x131433)
    /Users/Raghav/work/src/github.com/ttacon/libphonenumber/phonenumberutil.go:3066 +0x49
github.com/ttacon/libphonenumber.isNumberMatchWithOneNumber(0xc4201a0fc0, 0x132460, 0xa, 0x2)
    /Users/Raghav/work/src/github.com/ttacon/libphonenumber/phonenumberutil.go:3199 +0x16f
github.com/ttacon/libphonenumber.IsNumberMatch(0x132de0, 0xe, 0x132460, 0xa, 0x0)
    /Users/Raghav/work/src/github.com/ttacon/libphonenumber/phonenumberutil.go:3148 +0x275

**Comment by ttacon** [comment]
I can't repro this, so closing due to age.
