### ISSUE TITLE
Australian numbers incorrectly classified as having Italian leading zeros

### ISSUE THREAD

**Issue by alecthomas** [ttacon/libphonenumber#4]
All fixed line and mobile numbers in Australia have a zero prefix. eg. A mobile number looks like `0491 570 156` and a fixed line looks like `02 5550 1234`. The leading zero is dropped for international dialling. I believe there are many other countries using a similar approach.

Upstream [libphonenumber](http://libphonenumber.appspot.com) correctly parses and formats this as `+61491570156`, but this library does not and produces `+610491570156` (note the additional zero).

PS. I tried to dig through the code to track down where this was occurring, but the code is deeply deeply nested (presumably due to being translated from Java). Sorry I couldn't be of more help.

**Comment by ttacon** [comment]
Thanks for taking the time to track the bug down! I plan on making this idiomatic go soon, which should make going through everything drastically easier. (And you're right, it was super fun translating from Java :P).
