### ISSUE TITLE
panic with  "proto: nil destination" when trying to compare 2 numbers

### ISSUE THREAD

**Issue by raghav-g** [ttacon/libphonenumber#43]
`
	isMatch := libphonenumber.IsNumberMatch("+919573750192", "9573750192");
`

The above line throws an error -
 panic: proto: nil destination

**Comment by raghav-g** [comment]
`
	isMatch := libphonenumber.IsNumberMatch("+19573750192", "+19573750192");
`

This also happens if both numbers are same

**Comment by ttacon** [comment]
Fixed with https://github.com/ttacon/libphonenumber/pull/44
