### ISSUE TITLE
Add godeps.json

### ISSUE THREAD

**Issue by steelbrain** [ttacon/libphonenumber#48]
It'll help users not to have to figure out the dependencies on their own and will allow package managers like glide to do their job properly

**Comment by 17twenty** [comment]
Why can't you just use `go get -u github.com/ttacon/libphonenumber`?

What would a godeps.json add?

**Comment by steelbrain** [comment]
@17twenty I did try go get, but this package depends on external dependencies that are not automatically installed by go get. Adding a `Godeps` file would indicate the consumers which dependencies need to be installed

**Comment by 17twenty** [comment]
I couldn't repeat that issue. The issue with godeps is it links to a
package manager that may or may not be wanted as a dependency

**Comment by steelbrain** [comment]
That's not entire true, when you add Godeps state file, you are not actually tying this package to a package manager at all. It saves current state of dependencies of this package only, it'll only be used if the person downloading uses a package manager (almost all package managers eg. Glide, godep support this file), if they don't go-get will work just as fine as it does now.

**Comment by ttacon** [comment]
Feel free to open a PR addressing this @steelbrain!

**Comment by ttacon** [comment]
Hi @steelbrain, this project is now using `dep` - let me know if that solves your issue!
