### ISSUE TITLE
Issue in django-phonenumber-field causing by error in libphonenumber

### ISSUE THREAD

**Issue by AbdurRehman91** [ttacon/libphonenumber#50]
hi,actually the issue is in django-phonenumber-field and by that german numbers,for example 1765770313 is getting invalid in my application.So when i asked @django-phonenumber field,the response was 
"This is an issue in the upstream libphonenumber, probably stemming from a default country code not being set"...
so can you kindly tell me whats going on overall
thanks

**Comment by ttacon** [comment]
Hi! This is the Golang implementation of libphonenumber, so this isn't related to django-phonenumber-field. You're looking for the python version, which I believe is maintained by Google?

**Comment by AbdurRehman91** [comment]
yes sure i am looking for python one

**Comment by ttacon** [comment]
Cool, in that case I'll close this issue since this isn't the python implementation.
