### ISSUE TITLE
Test failed at f9c5ddf85ffa9cc802cb511f9ab4733d7d8fbb0e

### ISSUE THREAD

**Issue by deafwolf** [ttacon/libphonenumber#55]
github.com/ttacon/libphonenumber on master via python
➔ git log | head -1
commit f9c5ddf85ffa9cc802cb511f9ab4733d7d8fbb0e

github.com/ttacon/libphonenumber on master via python
➔ go test github.com/ttacon/libphonenumber
--- FAIL: TestGetExampleNumberForNonGeoEntity (0.00s)
	phonenumberutil_test.go:717: there should be an example 800 number
	phonenumberutil_test.go:722: there should be an example number for 979
FAIL
FAIL	github.com/ttacon/libphonenumber	0.016s

**Comment by nicpottier** [comment]
This was fixed in our port in case that's useful to someone (the logic was out of date, brought in from current Java impl):
  https://github.com/nyaruka/phonenumbers/commit/9c5a28db50f85d24a31e1e9cebb6bff9f6671913

**Comment by ttacon** [comment]
Feel free to open a PR!

**Comment by ttacon** [comment]
Tests are passing and happy again, closing, thanks for the report!
