### ISSUE TITLE
Tag semver releases?

### ISSUE THREAD

**Issue by akshayjshah** [ttacon/libphonenumber#56]
Hi! I notice that this project doesn't have any [tagged releases](https://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases). Would you mind adding some [SemVer](http://semver.org/)-compatible release tags? It would really, really help those of us using [`dep`](http://github.com/golang/dep) and similar tools.

**Comment by ttacon** [comment]
Totally, tagged!

**Comment by akshayjshah** [comment]
🎉 Thanks!

**Comment by ttacon** [comment]
np!
