### ISSUE TITLE
wrong validation result and mismatched from the official libphonenumber

### ISSUE THREAD

**Issue by nullne** [ttacon/libphonenumber#61]
this is the parsing result from [libphonenumber](http://libphonenumber.appspot.com/phonenumberparser?number=+856%202092420366&country=LA)

this is the result from this lib, the result is mismatch
```
     countryCode := 856
      mobileNumber := "2092420366"
      region := "LA"
      num, err := libphonenumber.Parse(fmt.Sprintf("+%d%s", countryCode, mobileNumber), region)
      if err != nil {
          fmt.Println(err)
          return
      }
      fmt.Println(libphonenumber.IsValidNumber(num))
      // false
```

what's wrong, should we upgrade the data source or something?

**Comment by ttacon** [comment]
Yup, probably a protobuf data update - I'll aim to address this in the next week (PRs welcome).

**Comment by nullne** [comment]
@ttacon  I'd like to. I have to go through your code if I have spare time. 
thank you for your time. and thank you very much if you could update it

**Comment by ttacon** [comment]
This should now be fixed, let me know if it isn't!
