### ISSUE TITLE
IsPossibleNumber returns false for valid numbers

### ISSUE THREAD

**Issue by shashankmehra** [ttacon/libphonenumber#63]
`IsPossibleNumber` seems to be returning `false` even for numbers which are valid according to `IsValidNumber`. I even tried using an example number via `GetExampleNumber` itself:

```go
num := libphonenumber.GetExampleNumber("IN")
is_valid := libphonenumber.IsValidNumber(num)
fmt.Printf("is_valid: %v\n", is_valid)
is_possible := libphonenumber.IsPossibleNumber(num)
fmt.Printf("is_possible: %v\n", is_possible)
formattedNum := libphonenumber.Format(num, libphonenumber.E164)
fmt.Printf("number: %v\n", formattedNum)
```

returns the output:
```
is_valid: true
is_possible: false
number: +911123456789
```

I tried this with my own number and even `GetExampleNumber("US")`.

**Comment by ttacon** [comment]
Well shoot, that's not good - I'll try to look into this soon. Some test cases that currently fail would also be great!

**Comment by ttacon** [comment]
This should now be fixed, let me know if it isn't!
