### ISSUE TITLE
Behaviour differs from javascript libphonenumber

### ISSUE THREAD

**Issue by ptman** [ttacon/libphonenumber#7]
Testing using <https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html>, the number '+358401234567' with region 'FI' includes '40' in national_number (as I would expect), while libphonenumber.Parse("+358401234567", "FI") doesn't.

**Comment by ttacon** [comment]
Ya, definitely an issue. I don't have a ton of time to work on it, but I should have some time soon to dig into it. Thanks for the report!

**Comment by ttacon** [comment]
Some super quick digging shows the "40" stripped off as the carrier code in line [2892](https://github.com/ttacon/libphonenumber/blob/master/phonenumberutil.go#L2892), but then not being classified as too short of a number. So it's possibly a metadata issue but I'm going to double check with the Java version as well. Just giving a heads up incase you have any time for digging into it!

**Comment by ptman** [comment]
Thank you for the quick reply. I'm not at all familiar with libphonenumber, but maybe I'll have enough time to dig through it in the near future.

**Comment by ttacon** [comment]
Fixed by #14
