### ISSUE TITLE
There is a  problem about libphonenumber  

### ISSUE THREAD

**Issue by GodSteven** [ttacon/libphonenumber#70]
Hi,ttacon,i use your libphonenumber in my go service，but recently i find a problem，for examople,16601047600 this a valid phonenumber from China Unicom，and it belongs to beijing，but when i use libphonenumber to parse this phonenumber,it tells me ,this number is not a valid number

**Comment by ttacon** [comment]
This should now be fixed, let me know if it's still an issue!
